### ISSUE TITLE
Navigator is not defined

### ISSUE THREAD

**Issue by warent** [tokuda109/next-useragent#1]
I'm just using it as shown in the example and I'm getting an error `ReferenceError: navigator is not defined`

**Comment by tokuda109** [comment]
@warent 

Thanks for report! I'll fix it.

**Comment by warent** [comment]
Thanks. This was on Firefox Quantum 67.0.1 by the way.

**Comment by tokuda109** [comment]
It fixed! Thank you for finding these.
