### ISSUE TITLE
issue when using getServerSideProps

### ISSUE THREAD

**Issue by joshkopecek** [tokuda109/next-useragent#177]
## When using getServerSideProps throws "You can not use getInitialProps with getServerSideProps"

I recently switched a few pages to `getServerSideProps`, but only one has `withUserAgent`. I'd like to use `getServerSideProps` on all of them, but it's currently impossible with this setup.

## To Reproduce

1. Switch to `getServerSideProps`
1. Wrap with `withUserAgent`
1. Try to render a page

## Expected behavior

It should detect if you're using `getServerSideProps`

**Comment by tokuda109** [comment]
@joshkopecek 

I'll fix it. m(_ _)m

**Comment by tokuda109** [comment]
@joshkopecek 

I fixed it with a pull request [here](https://github.com/tokuda109/next-useragent/pull/178).
It is now available as version `2.2.0`.

**Comment by alieslamifard** [comment]
Hi @tokuda109 
I faced this issue with Next.js `9.5.3`

This is my `getServerSideProps` according to your example:

```
export function getServerSideProps(context) {
    const ua = useUserAgent(context.req.headers['user-agent'])

    console.log('ua', ua);

    return {
        props: { ua, useragent: ua.source }
    }
}
```

Here is my console log:

```
ua {
  browser: 'Chrome',
  deviceType: undefined,
  os: 'Windows',
  isMobile: false,
  isTablet: false,
  isIos: false,
  source: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  deviceVendor: undefined,
  osVersion: 10,
  browserVersion: 85,
  isIphone: false,
  isIpad: false,
  isDesktop: true,
  isChrome: true,
  isFirefox: false,
  isSafari: false,
  isIE: false,
  isMac: false,
  isChromeOS: false,
  isWindows: true,
  isAndroid: false,
  isBot: false
}
SerializableError: Error serializing `.ua.deviceType` returned from `getServerSideProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value all together.
    at isSerializable (D:\Test\next-ua-test\my-app\node_modules\next\dist\lib\is-serializable-props.js:7:95)

```

I can wait for a fix or open a PR. As you wish. Thanks in advance.

**Comment by tokuda109** [comment]
@alieslamifard 
Thanks! Please open a pull request if you'd like.

**Comment by alieslamifard** [comment]
I've done it. @tokuda109  Thanks.
