### ISSUE TITLE
User Agent not detect the ipad and tablet devices 

### ISSUE THREAD

**Issue by danyalg** [tokuda109/next-useragent#223]
## 🐞 Describe the bug

User Agent not detect the ipad and tablet devices 

## To Reproduce

1. Go to to safari chose userAgent as ipad
2. check console return ua object 

browser: "Safari"

browserVersion: 13

deviceType: ipdad

deviceVendor: Apple

isAndroid: false

isBot: false

isChrome: false

isChromeOS: false

isDesktop: false

isFirefox: false

isIE: false

isIos: true

isIpad: true

isIphone: false

isMac: true

isMobile: false

isSafari: true

isTablet: true

isWindows: false

os: "Mac OS"

osVersion: 10

source: "\"Mozilla/

## Expected behavior

browser: "Safari"

browserVersion: 13

deviceType: null

deviceVendor: null

isAndroid: false

isBot: false

isChrome: false

isChromeOS: false

isDesktop: true

isFirefox: false

isIE: false

isIos: false

isIpad: false

isIphone: false

isMac: true

isMobile: false

isSafari: true

isTablet: false

isWindows: false

os: "Mac OS"

osVersion: 10

source: "\"Safari/

**Comment by tokuda109** [comment]
@danyalg 

I'll confirm it soon.

**Comment by tokuda109** [comment]
@danyalg 
As I wrote [here](https://github.com/tokuda109/next-useragent/issues/173), the behaviour of iPad/OS13 is correct.

**Comment by danyalg** [comment]
Thanks @tokuda109
