### ISSUE TITLE
Frozen (fixed) version of `ua-parser-js`

### ISSUE THREAD

**Issue by KODerFunk** [tokuda109/next-useragent#336]
## Frozen version of [ua-parser-js](https://github.com/faisalman/ua-parser-js) in `package.json`:

```json
"ua-parser-js": "0.7.23"
```

## To Reproduce

1. Add latest `next-useragent` to project (add `ua-parser-js@0.7.23`).
2. Add latest `ua-parser-js` to project (add `ua-parser-js@0.7.27` and move `ua-parser-js@0.7.23` to `node_modules/next-useragent/node_modules/ua-parser-js`).
3. Have both packages in bundle when use `ua-parser-js` directly in project.
4. I can't control freshness of `ua-parser-js` under hood of `next-useragent`.

## Expected behavior

1. Use major-version locking (`0.x.x`) via
```json
"ua-parser-js": "^0.7.23"
```
2. ...or minor-version locking (`0.7.x`) via
```json
"ua-parser-js": "~0.7.23"
```

**Comment by tokuda109** [comment]
@KODerFunk 

Thanks for the advice!
This has been fixed in version `2.4.1`.
