### ISSUE TITLE
ua undefined on Server Side

### ISSUE THREAD

**Issue by BjoernRave** [tokuda109/next-useragent#36]
On the server side the ua object is undefined for me

**Comment by tokuda109** [comment]
@BjoernRave 
Can you explain the steps in more detail?

**Comment by virgilbugnariu** [comment]
I am experiencing this as well with both class and functional components.
In the browser it seems to be working fine.

**Comment by pantchox** [comment]
same, in your readme example and the function example (in the issues section), i think something happend related to nextjs versions, i am using nextjs 9.2

**Comment by rabellino12** [comment]
same here using next 9.3.1 (latest currently), I just wrapped my component with your hoc `withUserAgent` and started next locally with `next` command

**Comment by rabellino12** [comment]
This can be related, maybe use getServerSideProps now? [https://nextjs.org/docs/api-reference/data-fetching/getInitialProps#recommended-use-getstaticprops-or-getserversideprops-instead](https://nextjs.org/docs/api-reference/data-fetching/getInitialProps#recommended-use-getstaticprops-or-getserversideprops-instead)

**Comment by tokuda109** [comment]
@rabellino12 
Thanks a lot!
I'll try to fix it this weekend.

**Comment by rabellino12** [comment]
@tokuda109 It worked, maybe the same people that have the problem here had the same mistake, is a rookie mistake on nextjs and i just got into this ssr thing, the HOC only works on pages, it won´t work on nested components, only on the page component.
Sorry to bother you with that

**Comment by tokuda109** [comment]
It looks fine, and close this.
