### ISSUE TITLE
useUserAgent hook is not a hook and the documentation breaks the rules of hooks

### ISSUE THREAD

**Issue by etler** [tokuda109/next-useragent#365]
I was looking at the source for [`useUserAgent`](https://github.com/tokuda109/next-useragent/blob/master/src/useUserAgent.ts) and saw that it doesn't actually use any react hook dependencies under the hood and follows the hook convention unnecessarily and it's a misnomer to call it a hook. The example in the documentation also breaks the rules of hooks by putting the hook in an `if else` statement.

I think it's confusing to give this function a name that implies that it's a hook when it doesn't actually use any hooks and doesn't actually need to follow the rules of hooks. I think it would make more sense to just name it as a utility function like `parseUserAgent` or something.

**Comment by svrakata** [comment]
I agree with @etler. It's also confusing about availability of the "hook" server side and it triggers eslint error. Workaround: 
```import { useUserAgent as parseUserAgent } from "next-useragent";```
Cheers

**Comment by carl0s-sa** [comment]
Is this change to be implemented? We are using it on server side as well and eslint doesn't like it.
If refactoring the hook to be a non-hook is too much of a breaking change maybe exposing the `parse` function removes the need for the workaround.
I can make a PR for this if needed.
