### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Andy671** [tokuda109/next-useragent#66]
First of all, thanks! Your package is great! 

## 🐞 Describe the bug
I have a lot of users with lots of different browsers and here is the issue some of them experience:

> TypeError: Cannot read property 'toLowerCase' of undefined     at parse (/SOURCE_TO_PROJECT/node_modules/next-useragent/dist/next-useragent.js:141:33)

--
In the source code, it directs to **line 141**
Here is it:
<pre><code>
function parse(phase) {
    ....
    var ua = Object.freeze({
        ...
        isBot: regex.test(phase.toLowerCase()), // THIS LINE CAUSES THE ISSUE
    });
    return ua;
}
</code></pre>

## To Reproduce
Occurs randomly

## Expected behavior
Proper handling: `undefined` check of `phase` object to make the app function without a crash.

## Your Environment
package.json:
`"next-useragent": "^2.0.2"`

mypage.js:
<pre><code>import { withUserAgent } from 'next-useragent'
...
export default withUserAgent(MyPage)
</code></pre>

**Comment by tokuda109** [comment]
@Andy671 
Sorry for the late reply.
Fixed new 2.1.0 version is released.

**Comment by Andy671** [comment]
@tokuda109 Thanks A Lot!
